// <auto-generated />
using System;
using LongDrive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LongDrive.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231026185852_updatedTellimus")]
    partial class updatedTellimus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LongDrive.Models.SoiduPaevik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Aeg")
                        .HasColumnType("datetime2");

                    b.Property<int>("TellimusId")
                        .HasColumnType("int");

                    b.Property<int>("VeoautoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TellimusId");

                    b.HasIndex("VeoautoId");

                    b.ToTable("SoiduPaevikud");
                });

            modelBuilder.Entity("LongDrive.Models.Soiduauto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<double>("Pikkus")
                        .HasColumnType("float");

                    b.Property<string>("Pilt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Soiduautod");
                });

            modelBuilder.Entity("LongDrive.Models.Tellimus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kirjeldus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vahemaa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tellimused");
                });

            modelBuilder.Entity("LongDrive.Models.Veoauto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Algus")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Lopp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<double>("Pikkus")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Veoautod");
                });

            modelBuilder.Entity("LongDrive.Models.SoiduPaevik", b =>
                {
                    b.HasOne("LongDrive.Models.Tellimus", "Tellimus")
                        .WithMany("SoiduPaevik")
                        .HasForeignKey("TellimusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LongDrive.Models.Veoauto", "Veoauto")
                        .WithMany("SoiduPaevik")
                        .HasForeignKey("VeoautoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tellimus");

                    b.Navigation("Veoauto");
                });

            modelBuilder.Entity("LongDrive.Models.Tellimus", b =>
                {
                    b.Navigation("SoiduPaevik");
                });

            modelBuilder.Entity("LongDrive.Models.Veoauto", b =>
                {
                    b.Navigation("SoiduPaevik");
                });
#pragma warning restore 612, 618
        }
    }
}
